apiVersion: v1
kind: Service
metadata:
  name: jdemo-heap-service
  namespace: gaguena-apps
spec:
  selector:
    app: jdemo-heap
  ports:
    - port: 8080        # porta do Service
      targetPort: 8080  # porta do container
  type: ClusterIP