apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jdemo-heap-ingress
  namespace: gaguena-apps
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: jdemo-heap
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: app-demo-service
            port:
              number: 8080