apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jdemo-heap-ingress
  namespace: gaguena-apps
spec:
  ingressClassName: nginx
  rules:
  - host: jdemo-heap.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jdemo-heap-service
            port:
              number: 8080